version: '3'

services:
  postgres:
    container_name: studs-db
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres_db:/data/postgres