spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user?stringtype=unspecified
    username: user
    password: password
  flyway:
    user: user
    password: password

springdoc:
  api-docs:
    path: /api-docs

amazon:
  s3:
    bucketName: studs

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/user
    username: user
    password: password

---
spring:
  config:
    activate:
      on-profile: local_docker
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/user
    username: user
    password: password